apiVersion: batch/v1
kind: CronJob
metadata:
  name: dnsupdater
  namespace: dnsupdater
spec:
  schedule: "*/15  * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
          - name: dnsupdatervolume
            persistentVolumeClaim:
              claimName: dnsupdater-pvc
          containers:
          - name: dnsupdater
            image: registry.wieru.com/dnsupdater
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                memory: "64Mi"
                cpu: "250m"
              limits:
                memory: "128Mi"
                cpu: "500m"
            envFrom:
            - configMapRef:
                name: dnsupdaterconfig
            - secretRef:
                name: dnsupdatersecret
            volumeMounts:
            - mountPath: /log
              name: dnsupdatervolume